name: Build and deploy Java app to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Java 17 설정 (필요시 너 버전에 맞게 수정)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven 빌드 실행 (pom.xml이 board-app 내부에 있다고 가정)
      - name: Build with Maven
        run: mvn clean package --file board-api/pom.xml

      # 4. Azure App Service에 배포
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <mini-was>             # ⬅ 여기에 Azure App Service 이름 입력
          slot-name: production
          package: board-api/target/*.jar               # ⬅ jar 파일 경로 (확인 필요)
